apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mairror-prod
spec:
  acme:
    email: "{{ .Values.email }}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: mairror-issuer-account-key
    solvers:
      - dns01:
          route53:
            region: "{{ .Values.aws.region }}"
            hostedZoneID: "{{ .Values.aws.hostedzoneID }}"
